### ISSUE TITLE
Sensor-Offset Temperature

### ISSUE THREAD

**Issue by rbrixel** [rbrixel/opensrvmini#13]
Two different offset-values for the temperature-sensors (bme and ds) so that the user can self calibrate the sensors. ideally in the app

**Comment by dalander** [comment]
Now in Develop,
Constructors accepts temperatureOffset that will be added to the measured temperature.
Offset can be positive and negative.

**Comment by rbrixel** [comment]
> Now in Develop,
> Constructors accepts temperatureOffset that will be added to the measured temperature.
> Offset can be positive and negative.

Great!!!
